apiVersion: v1
kind: Service
metadata:
  name: scaletest-service
spec:
  selector:
    app: scaletest-app
  ports:
    - port: 80          # порт, по которому будем обращаться из-вне
      targetPort: 8080  # порт контейнера
  type: ClusterIP
  